# Generated by Django 4.2.13 on 2024-07-09 22:45

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='N/A')),
                ('description', models.CharField(db_index=True, default='N/A')),
                ('text', models.CharField(db_index=True, default='N/A')),
                ('status_date', models.DateField(default='1970-1-1', verbose_name='status date')),
                ('url', models.CharField(default='legiscan.com')),
                ('status', models.CharField(default='N/A')),
                ('state', models.CharField(default='N/A', max_length=3)),
                ('bill_number', models.CharField(default='N/A')),
                ('bill_type', models.CharField(default='N/A')),
                ('primary_sponsor', models.CharField(db_index=True, default='N/A')),
                ('total_sponsors', models.IntegerField(default=0)),
                ('content_type', models.CharField(default='N/A')),
                ('agency', models.CharField(default='N/A')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
    ]
