# Generated by Django 4.2.13 on 2024-07-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='state',
            field=models.CharField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status_date',
            field=models.DateField(default='1970-1-1'),
        ),
    ]
