# Generated by Django 4.2.13 on 2024-07-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_bill_state_alter_bill_status_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='agency',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='content_type',
            new_name='source',
        ),
    ]
