# Generated by Django 4.2.13 on 2024-07-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_rename_agency_bill_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='collection',
            new_name='temp1',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='source',
            new_name='temp2',
        ),
    ]
