# Generated by Django 4.2.13 on 2024-07-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_rename_collection_bill_temp1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='temp1',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='temp2',
            new_name='source',
        ),
    ]
