# Generated by Django 4.2.13 on 2024-07-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_rename_temp1_bill_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='collection',
            new_name='content_collection',
        ),
    ]
