# Generated by Django 4.2.13 on 2024-07-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_remove_bill_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='keyword_algorithm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='keyword_artificial_intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='keyword_computer_decision',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='keyword_machine_learning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='keyword_neural_network',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='total_keywords',
            field=models.IntegerField(default=0),
        ),
    ]
