# Generated by Django 4.2.13 on 2024-07-16 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_bill_keyword_algorithm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='keyword_computer_decision',
            new_name='keyword_automated_decision',
        ),
    ]
