# Generated by Django 4.2.13 on 2024-08-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_rename_keyword_computer_decision_bill_keyword_automated_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='last_action',
            field=models.CharField(default='N/A'),
        ),
        migrations.AddField(
            model_name='bill',
            name='last_action_date',
            field=models.DateField(default='1970-1-1'),
        ),
    ]
