# Generated by Django 4.2.13 on 2024-08-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_rename_other_bill_other_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='social_impact',
            new_name='societal_impact',
        ),
    ]
