# Generated by Django 4.2.13 on 2024-08-15 22:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_rename_keyword_recommenation_system_bill_keyword_recommendation_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='keyword_instances',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=list, size=None),
        ),
    ]
