# Generated by Django 4.2.13 on 2024-08-16 18:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_bill_keyword_instances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='keyword_instances',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None),
        ),
    ]
