# Generated by Django 4.2.13 on 2025-03-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0020_alter_bill_keyword_instances"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="summary",
            field=models.CharField(default="N/A"),
        ),
    ]
