# Generated by Django 5.0.7 on 2025-03-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_alter_bill_keyword_instances'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='summary',
            field=models.CharField(default='N/A'),
        ),
    ]
